services:
  db:
    container_name: projeto-final
    image: postgres:16-alpine
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - internal_network

volumes:
  postgres_data:


networks:
  internal_network:
    driver: bridge
